plant_dict = {
    'Rosemary':         {'scientific_name': 'Salvia rosmarinus',   'type': 'herb',       'state': 'plant',  'position': '%[75,100]',  'water_schedule': ('day', 1),  'water_amount': 5,  'present': 'yes'},
    'Gold-Leaf-Thyme':  {'scientific_name': 'Thymus citriodorus',  'type': 'herb',       'state': 'plant',  'position': '%[85,50]',   'water_schedule': ('week', 3),  'water_amount': 8,  'present': 'yes'},
    'Sage':             {'scientific_name': 'Salvia officinalis',  'type': 'herb',       'state': 'plant',  'position': '%[75,100]',    'water_schedule': ('week', 3),  'water_amount': 5,  'present': 'yes'},
    'Shishito-Peppers': {'scientific_name': 'Capsicum annuum',     'type': 'pepper',     'state': 'seed',   'position': '%[65,50]',   'water_schedule': ('day', 1),  'water_amount': 5,  'present': 'yes'},
    'Jade-Plant':       {'scientific_name': 'Crassula ovata',      'type': 'succulent',  'state': 'plant',  'position': '%[0,0]',  'water_schedule': ('week', 3),  'water_amount': 5,  'present': 'yes'},
    'Ponthos':          {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[100,100]',    'water_schedule': ('day', 1),  'water_amount': 8,  'present': 'yes'},
    'Chives':           {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[35,0-100]',    'water_schedule': ('week', 3),  'water_amount': 5,  'present': 'yes'},
    'Lavendar':         {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[20,0-100]',    'water_schedule': ('week', 3),  'water_amount': 5,  'present': 'yes'},
    'Parsley':          {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[9,0-100]',    'water_schedule': ('week'  ,3),  'water_amount': 5,  'present': 'yes'},
    'Basil':            {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[55,0]',    'water_schedule': ('day', 1),  'water_amount': 5,  'present': 'yes'},
    'Spearmint':        {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '%[55,100]',    'water_schedule': ('day', 1),  'water_amount': 5,  'present': 'yes'},
}
    #'Chives':           {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '[%[35,0-100), %(40,100)]',    'water_schedule': ('day'  ,1),  'water_amount': 8,  'present': 'yes'},
    #'Lavendar':         {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '[%[20,0-100), %(24,0-100)]',    'water_schedule': ('day'  ,1),  'water_amount': 8,  'present': 'yes'},
    #'Parsley':          {'scientific_name': 'Epipremnum aureum',   'type': 'plant',      'state': 'plant',  'position': '[%[9,0-100), %(5,0-100)]',
